services:
  - type: web
    name: netflix-cookie-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        scope: run
        value: 8933917086
      - key: WEBHOOK_URL
        scope: run
        value: https://net2bot.onrender.com
      - key: PORT
        scope: run
        value: "8000"
